parameters:
- name : serviceConnection

steps:
- download: current
  artifact: drop

- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      $(Pipeline.Workspace)/drop/**/variables.tf
      $(Pipeline.Workspace)/drop/**/providers.tf
    verbosity: detailed
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: TerraformInstaller@0
  displayName: "Install Terraform Latest"
  inputs:
    terraformVersion: latest

- task: AzureCLI@2
  displayName: "Set Storage Access key"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      STORAGE_ACCOUNT_KEY = $(az storage account keys list -g marketplace-admin-rg -n mktadminstore --query [0].value -o tsv)
      echo "setting storage account key variable"
      echo "##vso[task.setvariable variable=ARM_ACCESS_KEY;issecret=true]$STORAGE_ACCOUNT_KEY"

- task: TerraformCLI@0
  displayName: 'Initialize Terraform'
  inputs:
    command: 'init'
    workingDirectory: '$(Pipeline.Workspace)/drop/terraform/'
    backendServiceArm: '${{ parameters.serviceConnection }}'

