trigger:
  branches:
    include:
      - master

variables:
  - template: variables/build.yml

stages:
  - stage: 'Build'
    displayName: 'Build Terraform IAC'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: '$(buildVmImage)'

        steps:
          - task: CopyFiles@2
            displayName: 'Copy Terraform code'
            inputs:
              sourceFolder: 'terraform'
              contents: '**/*'
              targetFolder: '$(Build.ArtifactStagingDirectory)/terraform'
              cleanTargetFolder: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Terraform Code: drop'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)'
