parameters:
- name : serviceConnection

steps:
- download: current
  artifact: drop

- task: qetza.replacetokens.replacetokens-task.replacetokens@5
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      $(Pipeline.Workspace)/drop/**/variables.tf
    verbosity: detailed
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: TerraformInstaller@0
  displayName: "Install Terraform Latest"
  inputs:
    terraformVersion: latest
