variables:
- name: terraform-state-key
  value: 'dev.terraform.tfstate'
- name: resource_group_location
  value: australiaeast
- name: environment
  value: dev
- name: project
  value: Marketplace
- name: app_service_sku
  value: B1
- name: app_service_os
  value: Linux
- name: company_name
  value: MarketAgora
- name: company_email
  value: rimazmohommed523@gmail.com
- name: apim_sku
  value: Consumption_0
- name: api_domain_url
  value: "https://marketplace-dev-dotnet-api.azurewebsites.net"
